# Generated by Django 5.2.10 on 2026-01-09 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('queued', 'Na Fila'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou'), ('skipped', 'Ignorado')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('queued_at', models.DateTimeField(blank=True, null=True, verbose_name='Enfileirado em')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
            ],
            options={
                'verbose_name': 'Destinatário da Campanha',
                'verbose_name_plural': 'Destinatários da Campanha',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Campanha')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendada'), ('running', 'Em Execução'), ('paused', 'Pausada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Status')),
                ('campaign_type', models.CharField(choices=[('instant', 'Disparo Imediato'), ('scheduled', 'Agendada'), ('recurring', 'Recorrente')], default='instant', max_length=20, verbose_name='Tipo de Campanha')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Agendada para')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='Total de Destinatários')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Enviadas')),
                ('delivered_count', models.PositiveIntegerField(default=0, verbose_name='Entregues')),
                ('read_count', models.PositiveIntegerField(default=0, verbose_name='Lidas')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Falhas')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciada em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluída em')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='Pausada em')),
                ('messages_per_minute', models.PositiveIntegerField(default=20, help_text='Limite de mensagens por minuto para esta campanha', verbose_name='Mensagens por Minuto')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Campanha',
                'verbose_name_plural': 'Campanhas',
                'ordering': ['-created_at'],
            },
        ),
    ]
