# Generated by Django 5.2.10 on 2026-01-09 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('messaging', '0001_initial'),
        ('supporters', '0002_add_system_tags_fields'),
        ('whatsapp', '0002_remove_whatsappsession_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='message_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='messaging.messagetemplate', verbose_name='Template de Mensagem'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='supporters.segment', verbose_name='Segmento'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Filtrar por tags específicas (além do segmento)', related_name='campaigns', to='supporters.tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='whatsapp_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='whatsapp.whatsappsession', verbose_name='Sessão WhatsApp'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaigns.campaign', verbose_name='Campanha'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_recipients', to='messaging.message', verbose_name='Mensagem'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_recipients', to='supporters.supporter', verbose_name='Apoiador'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'scheduled_at'], name='campaigns_c_status_4a521f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'created_at'], name='campaigns_c_status_6076a2_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_1a8cf7_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['status', 'created_at'], name='campaigns_c_status_bac7c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together={('campaign', 'supporter')},
        ),
    ]
