# Generated by Django 5.2.10 on 2026-01-09 22:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
        ('supporters', '0002_add_system_tags_fields'),
        ('whatsapp', '0002_remove_whatsappsession_qr_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('queued', 'Na Fila'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falha')], default='pending', max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Mensagem (API)')),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item da Campanha',
                'verbose_name_plural': 'Itens da Campanha',
            },
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='campaignrecipient',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaignrecipient',
            name='message',
        ),
        migrations.RemoveField(
            model_name='campaignrecipient',
            name='supporter',
        ),
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaigns_c_status_4a521f_idx',
        ),
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaigns_c_status_6076a2_idx',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='campaign_type',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='delivered_count',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='failed_count',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='message_template',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='messages_per_minute',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='paused_at',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='read_count',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='sent_count',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='tags',
        ),
        migrations.AddField(
            model_name='campaign',
            name='media_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tipo de Mídia'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='media_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL da Mídia'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='message',
            field=models.TextField(default='', verbose_name='Mensagem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='messages_delivered',
            field=models.IntegerField(default=0, verbose_name='Entregues'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='messages_failed',
            field=models.IntegerField(default=0, verbose_name='Falhas'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='messages_read',
            field=models.IntegerField(default=0, verbose_name='Lidas'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='messages_sent',
            field=models.IntegerField(default=0, verbose_name='Enviadas'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_groups',
            field=models.JSONField(blank=True, default=list, help_text='Lista de grupos fixos: leads, supporters, team', verbose_name='Grupos Alvo'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='supporters.segment', verbose_name='Segmento Alvo'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_tags',
            field=models.ManyToManyField(blank=True, to='supporters.tag', verbose_name='Tags Alvo'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendada'), ('running', 'Em Andamento'), ('paused', 'Pausada'), ('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('failed', 'Falhou')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='total_recipients',
            field=models.IntegerField(default=0, verbose_name='Total de Destinatários'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='whatsapp_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='whatsapp.whatsappsession', verbose_name='Sessão do WhatsApp'),
        ),
        migrations.AddField(
            model_name='campaignitem',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaignitem',
            name='supporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_messages', to='supporters.supporter'),
        ),
        migrations.DeleteModel(
            name='CampaignRecipient',
        ),
        migrations.AddIndex(
            model_name='campaignitem',
            index=models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_8ae203_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignitem',
            index=models.Index(fields=['message_id'], name='campaigns_c_message_5c6ff0_idx'),
        ),
    ]
