version: "3.8"

# ==========================================
# VoxPop - Docker Stack para Producao
# Deploy: docker stack deploy -c docker-stack.yml voxpop
# ==========================================

services:
  # ==========================================
  # VoxPop App (Django + Frontend estatico)
  # ==========================================
  voxpop_app:
    image: ${DOCKER_REGISTRY:-lpcoutinho}/voxpop:${VERSION:-latest}
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2 --worker-class gthread
    entrypoint: /entrypoint.sh

    volumes:
      - voxpop_static:/app/staticfiles
      - voxpop_media:/app/media

    networks:
      - voxpop_internal
      - traefik_public

    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DB_HOST=voxpop_db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_URL=redis://voxpop_redis:6379/0
      - CELERY_BROKER_URL=redis://voxpop_redis:6379/1
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - CORS_ALLOWED_ORIGINS=${FRONTEND_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - RUN_MIGRATIONS=1

    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 256M
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 10s
      labels:
        - traefik.enable=true
        - traefik.http.routers.voxpop.rule=Host(`${DOMAIN}`)
        - traefik.http.routers.voxpop.entrypoints=websecure
        - traefik.http.routers.voxpop.tls.certresolver=letsencryptresolver
        - traefik.http.services.voxpop.loadbalancer.server.port=8000
        - traefik.http.services.voxpop.loadbalancer.passHostHeader=true
        - traefik.http.middlewares.voxpop-headers.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.voxpop.middlewares=voxpop-headers

  # ==========================================
  # Celery Worker
  # ==========================================
  voxpop_celery:
    image: ${DOCKER_REGISTRY:-lpcoutinho}/voxpop:${VERSION:-latest}
    command: celery -A config worker -l INFO -Q default,campaigns,messages_high,messages_low,webhooks,analytics -c 4 --max-tasks-per-child=100

    networks:
      - voxpop_internal

    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DB_HOST=voxpop_db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_URL=redis://voxpop_redis:6379/0
      - CELERY_BROKER_URL=redis://voxpop_redis:6379/1
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 256M

  # ==========================================
  # Celery Beat (Scheduler)
  # ==========================================
  voxpop_beat:
    image: ${DOCKER_REGISTRY:-lpcoutinho}/voxpop:${VERSION:-latest}
    command: celery -A config beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler

    networks:
      - voxpop_internal

    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=config.settings.production
      - DB_HOST=voxpop_db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_URL=redis://voxpop_redis:6379/0
      - CELERY_BROKER_URL=redis://voxpop_redis:6379/1

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  # ==========================================
  # PostgreSQL
  # ==========================================
  voxpop_db:
    image: postgres:15-alpine
    command: postgres -c 'max_connections=200' -c 'shared_buffers=256MB'

    volumes:
      - voxpop_postgres:/var/lib/postgresql/data

    networks:
      - voxpop_internal

    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=America/Sao_Paulo

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.25"
          memory: 256M

  # ==========================================
  # Redis
  # ==========================================
  voxpop_redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

    volumes:
      - voxpop_redis:/data

    networks:
      - voxpop_internal

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.1"
          memory: 64M

volumes:
  voxpop_postgres:
    external: true
  voxpop_redis:
    external: true
  voxpop_static:
    external: true
  voxpop_media:
    external: true

networks:
  voxpop_internal:
    driver: overlay
    attachable: true
  traefik_public:
    external: true
