# Generated by Django 5.2.9 on 2026-01-09 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('role', models.CharField(choices=[('admin', 'Administrador do Tenant'), ('coordinator', 'Coordenador'), ('operator', 'Operador'), ('analyst', 'Analista'), ('volunteer', 'Voluntário')], default='volunteer', max_length=20, verbose_name='Função')),
                ('department', models.CharField(blank=True, choices=[('political', 'Político'), ('communication', 'Comunicação'), ('mobilization', 'Mobilização'), ('data', 'Dados e Análise'), ('finance', 'Financeiro'), ('volunteers', 'Voluntariado')], max_length=50, verbose_name='Departamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_team_members', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Membro da Equipe',
                'verbose_name_plural': 'Membros da Equipe',
                'ordering': ['user__first_name', 'user__last_name'],
                'unique_together': {('user',)},
            },
        ),
    ]
