# Generated by Django 5.2.10 on 2026-01-09 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('new_supporters', models.PositiveIntegerField(default=0, verbose_name='Novos Apoiadores')),
                ('total_supporters', models.PositiveIntegerField(default=0, verbose_name='Total de Apoiadores')),
                ('messages_sent', models.PositiveIntegerField(default=0, verbose_name='Mensagens Enviadas')),
                ('messages_delivered', models.PositiveIntegerField(default=0, verbose_name='Mensagens Entregues')),
                ('messages_read', models.PositiveIntegerField(default=0, verbose_name='Mensagens Lidas')),
                ('messages_failed', models.PositiveIntegerField(default=0, verbose_name='Mensagens com Falha')),
                ('campaigns_created', models.PositiveIntegerField(default=0, verbose_name='Campanhas Criadas')),
                ('campaigns_completed', models.PositiveIntegerField(default=0, verbose_name='Campanhas Concluídas')),
                ('delivery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa de Entrega (%)')),
                ('read_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa de Leitura (%)')),
            ],
            options={
                'verbose_name': 'Métricas Diárias',
                'verbose_name_plural': 'Métricas Diárias',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='Total de Destinatários')),
                ('sent', models.PositiveIntegerField(default=0, verbose_name='Enviadas')),
                ('delivered', models.PositiveIntegerField(default=0, verbose_name='Entregues')),
                ('read', models.PositiveIntegerField(default=0, verbose_name='Lidas')),
                ('failed', models.PositiveIntegerField(default=0, verbose_name='Falhas')),
                ('delivery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa de Entrega (%)')),
                ('read_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa de Leitura (%)')),
                ('failure_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa de Falha (%)')),
                ('avg_delivery_time_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo Médio de Entrega (s)')),
                ('last_calculated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='campaigns.campaign', verbose_name='Campanha')),
            ],
            options={
                'verbose_name': 'Métricas da Campanha',
                'verbose_name_plural': 'Métricas das Campanhas',
            },
        ),
    ]
