# Generated by Django 5.2.9 on 2025-12-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(help_text='Nome amigável para identificar a sessão', max_length=100, verbose_name='Nome da Sessão')),
                ('instance_name', models.CharField(help_text='Nome único da instância na Evolution API', max_length=100, unique=True, verbose_name='Nome da Instância')),
                ('status', models.CharField(choices=[('disconnected', 'Desconectado'), ('connecting', 'Conectando'), ('connected', 'Conectado'), ('banned', 'Banido')], default='disconnected', max_length=20, verbose_name='Status')),
                ('phone_number', models.CharField(blank=True, help_text='Número do WhatsApp conectado à sessão', max_length=20, verbose_name='Número Conectado')),
                ('qr_code', models.TextField(blank=True, help_text='QR Code em base64 para conexão', verbose_name='QR Code')),
                ('qr_code_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='QR Code Gerado em')),
                ('webhook_url', models.URLField(blank=True, help_text='URL configurada para receber eventos', verbose_name='URL do Webhook')),
                ('daily_message_limit', models.PositiveIntegerField(default=1000, verbose_name='Limite Diário de Mensagens')),
                ('messages_sent_today', models.PositiveIntegerField(default=0, verbose_name='Mensagens Enviadas Hoje')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Mensagem em')),
                ('last_health_check', models.DateTimeField(blank=True, null=True, verbose_name='Último Health Check')),
                ('is_healthy', models.BooleanField(default=False, verbose_name='Está Saudável')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Sessão WhatsApp',
                'verbose_name_plural': 'Sessões WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('event_type', models.CharField(help_text='Tipo do evento recebido da Evolution API', max_length=50, verbose_name='Tipo de Evento')),
                ('payload', models.JSONField(help_text='Payload JSON completo do webhook', verbose_name='Payload')),
                ('processed', models.BooleanField(default=False, verbose_name='Processado')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('error', models.TextField(blank=True, help_text='Mensagem de erro se o processamento falhou', verbose_name='Erro')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='whatsapp.whatsappsession', verbose_name='Sessão')),
            ],
            options={
                'verbose_name': 'Log de Webhook',
                'verbose_name_plural': 'Logs de Webhook',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'event_type'], name='whatsapp_we_session_7b270e_idx'), models.Index(fields=['processed', 'created_at'], name='whatsapp_we_process_3d1ee9_idx'), models.Index(fields=['event_type', 'processed'], name='whatsapp_we_event_t_a00b12_idx')],
            },
        ),
    ]
