# Generated by Django 5.2.9 on 2026-01-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappsession',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='whatsappsession',
            name='qr_code_generated_at',
        ),
        migrations.AddField(
            model_name='whatsappsession',
            name='access_token',
            field=models.CharField(blank=True, help_text='Token de acesso da instância na Evolution API', max_length=255, verbose_name='Access Token'),
        ),
    ]
