# Generated by Django 5.2.10 on 2026-01-09 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('supporters', '0002_add_system_tags_fields'),
        ('whatsapp', '0002_remove_whatsappsession_qr_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Template')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('document', 'Documento'), ('audio', 'Áudio'), ('video', 'Vídeo')], default='text', max_length=20, verbose_name='Tipo de Mensagem')),
                ('content', models.TextField(help_text='Texto da mensagem. Suporta variáveis: {{name}}, {{city}}, etc.', verbose_name='Conteúdo')),
                ('media_url', models.URLField(blank=True, help_text='URL da imagem, documento, áudio ou vídeo', verbose_name='URL da Mídia')),
                ('media_filename', models.CharField(blank=True, max_length=255, verbose_name='Nome do Arquivo')),
                ('media_mimetype', models.CharField(blank=True, max_length=100, verbose_name='Tipo MIME')),
                ('variables', models.JSONField(default=list, help_text='Lista de variáveis disponíveis no template', verbose_name='Variáveis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_templates', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Template de Mensagem',
                'verbose_name_plural': 'Templates de Mensagem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('phone', models.CharField(help_text='Número do destinatário no formato E.164', max_length=20, verbose_name='Telefone')),
                ('content', models.TextField(help_text='Conteúdo renderizado da mensagem', verbose_name='Conteúdo')),
                ('message_type', models.CharField(max_length=20, verbose_name='Tipo de Mensagem')),
                ('media_url', models.URLField(blank=True, verbose_name='URL da Mídia')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('queued', 'Na Fila'), ('sent', 'Enviada'), ('delivered', 'Entregue'), ('read', 'Lida'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID da mensagem na Evolution API', max_length=100, verbose_name='ID Externo')),
                ('whatsapp_message_id', models.CharField(blank=True, help_text='ID da mensagem no WhatsApp', max_length=100, verbose_name='ID WhatsApp')),
                ('queued_at', models.DateTimeField(blank=True, null=True, verbose_name='Enfileirada em')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada em')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Entregue em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Falhou em')),
                ('error_code', models.CharField(blank=True, max_length=50, verbose_name='Código de Erro')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='campaigns.campaign', verbose_name='Campanha')),
                ('supporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='supporters.supporter', verbose_name='Apoiador')),
                ('whatsapp_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='whatsapp.whatsappsession', verbose_name='Sessão WhatsApp')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.messagetemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['external_id'], name='messaging_m_externa_cc5500_idx'), models.Index(fields=['phone', 'status'], name='messaging_m_phone_8a8cd9_idx'), models.Index(fields=['campaign', 'status'], name='messaging_m_campaig_75e4de_idx'), models.Index(fields=['status', 'created_at'], name='messaging_m_status_17edaf_idx')],
            },
        ),
    ]
