# Generated by Django 5.2.15 on 2026-06-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='signature',
            field=models.TextField(blank=True, help_text='Assinatura ao final da mensagem. Suporta variáveis: {{name}}, {{city}}, etc.', verbose_name='Assinatura'),
        ),
    ]
