# Generated by Django 5.2.9 on 2025-12-11 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('phone', models.CharField(help_text='Número no formato E.164 (+5511999999999)', max_length=20, unique=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('electoral_zone', models.CharField(blank=True, max_length=10, verbose_name='Zona Eleitoral')),
                ('electoral_section', models.CharField(blank=True, max_length=10, verbose_name='Seção Eleitoral')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Gênero')),
                ('whatsapp_opt_in', models.BooleanField(default=False, help_text='Consentiu receber mensagens via WhatsApp', verbose_name='Opt-in WhatsApp')),
                ('opt_in_date', models.DateTimeField(blank=True, null=True, verbose_name='Data do Opt-in')),
                ('source', models.CharField(choices=[('import', 'Importação'), ('form', 'Formulário'), ('manual', 'Cadastro Manual'), ('api', 'API')], default='manual', max_length=50, verbose_name='Origem')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Campos adicionais em formato JSON', verbose_name='Dados Extras')),
            ],
            options={
                'verbose_name': 'Apoiador',
                'verbose_name_plural': 'Apoiadores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('color', models.CharField(default='#6366f1', help_text='Cor em formato hexadecimal (#RRGGBB)', max_length=7, verbose_name='Cor')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Segmento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('filters', models.JSONField(default=dict, help_text='Critérios de filtro em formato JSON', verbose_name='Filtros')),
                ('cached_count', models.PositiveIntegerField(default=0, verbose_name='Contagem (Cache)')),
                ('cached_at', models.DateTimeField(blank=True, null=True, verbose_name='Cache Atualizado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segments', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Segmento',
                'verbose_name_plural': 'Segmentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupporterTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter_tags', to='supporters.supporter', verbose_name='Apoiador')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter_tags', to='supporters.tag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag do Apoiador',
                'verbose_name_plural': 'Tags dos Apoiadores',
                'unique_together': {('supporter', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='supporter',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='supporters', through='supporters.SupporterTag', to='supporters.tag', verbose_name='Tags'),
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('file_path', models.CharField(max_length=500, verbose_name='Caminho do Arquivo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('total_rows', models.PositiveIntegerField(default=0, verbose_name='Total de Linhas')),
                ('processed_rows', models.PositiveIntegerField(default=0, verbose_name='Linhas Processadas')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Sucessos')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Erros')),
                ('skipped_count', models.PositiveIntegerField(default=0, help_text='Registros ignorados (duplicados, etc)', verbose_name='Ignorados')),
                ('errors_log', models.JSONField(default=list, help_text='Lista de erros encontrados durante importação', verbose_name='Log de Erros')),
                ('column_mapping', models.JSONField(default=dict, help_text='Correspondência entre colunas do arquivo e campos do modelo', verbose_name='Mapeamento de Colunas')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('auto_tags', models.ManyToManyField(blank=True, help_text='Tags a serem aplicadas automaticamente aos apoiadores importados', related_name='import_jobs', to='supporters.tag', verbose_name='Tags Automáticas')),
            ],
            options={
                'verbose_name': 'Job de Importação',
                'verbose_name_plural': 'Jobs de Importação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supporter',
            index=models.Index(fields=['phone'], name='supporters__phone_d73adb_idx'),
        ),
        migrations.AddIndex(
            model_name='supporter',
            index=models.Index(fields=['city', 'neighborhood'], name='supporters__city_7c4245_idx'),
        ),
        migrations.AddIndex(
            model_name='supporter',
            index=models.Index(fields=['state', 'city'], name='supporters__state_16ce43_idx'),
        ),
        migrations.AddIndex(
            model_name='supporter',
            index=models.Index(fields=['whatsapp_opt_in'], name='supporters__whatsap_0a6fdb_idx'),
        ),
    ]
