# Generated by Django 5.2.10 on 2026-01-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, verbose_name='Forçar troca de senha'),
        ),
    ]
