# Generated by Django 5.2.9 on 2025-12-11 19:44

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Organização')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('document', models.CharField(help_text='CNPJ da organização (formato: XX.XXX.XXX/XXXX-XX)', max_length=18, unique=True, verbose_name='CNPJ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Configurações personalizadas do tenant em JSON', verbose_name='Configurações')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('max_supporters', models.IntegerField(help_text='Número máximo de apoiadores cadastrados', verbose_name='Máximo de Apoiadores')),
                ('max_messages_month', models.IntegerField(help_text='Número máximo de mensagens enviadas por mês', verbose_name='Mensagens por Mês')),
                ('max_campaigns', models.IntegerField(help_text='Número máximo de campanhas ativas simultaneamente', verbose_name='Máximo de Campanhas')),
                ('max_whatsapp_sessions', models.IntegerField(help_text='Número máximo de sessões WhatsApp conectadas', verbose_name='Sessões WhatsApp')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Mensal')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Features adicionais do plano em JSON', verbose_name='Features')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_public', models.BooleanField(default=True, help_text='Se o plano aparece na página de preços', verbose_name='Público')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.client')),
            ],
            options={
                'verbose_name': 'Domínio',
                'verbose_name_plural': 'Domínios',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='tenants.plan', verbose_name='Plano'),
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Proprietário'), ('admin', 'Administrador'), ('operator', 'Operador'), ('viewer', 'Visualizador')], default='viewer', max_length=20, verbose_name='Papel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.client', verbose_name='Tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Membro do Tenant',
                'verbose_name_plural': 'Membros do Tenant',
                'ordering': ['tenant', 'role', 'user'],
                'unique_together': {('user', 'tenant')},
            },
        ),
    ]
