# Generated by Django 5.2.9 on 2025-12-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.CharField(blank=True, help_text='CNPJ da organização (formato: XX.XXX.XXX/XXXX-XX)', max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
